# Generated by Django 5.0.4 on 2024-05-26 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_admin_booking_event_hall_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventDateTime',
            new_name='event_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventName',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='hallName',
            new_name='hall_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adminId',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bookingId',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bookingTime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='hallId',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sendTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinfo1',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo1',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
