# Generated by Django 5.0.4 on 2024-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_eventdatetime_event_event_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo1',
            name='mail',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
