# Generated by Django 5.0.4 on 2024-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_userinfo1_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo1',
            name='mail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
