# Generated by Django 5.0.4 on 2024-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_userinfo1_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo1',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='confirm_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userinfo1',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
