# Generated by Django 5.0.4 on 2024-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_userinfo1_age_userinfo1_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo1',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Marriage', 'Marriage'), ('Conference', 'Conference'), ('New Product Launch', 'New Product Launch'), ('Musical Event for New Year', 'Musical Event for New Year')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
